[project]
name = "metador-extension-cookiecutter"
version = "0.1.0"
description = "Cookiecutter template to create Python packages providing Metador plugins."

license = "MIT"
keywords = [
    "metador",
    "fair",
    "metadata",
    "python",
    "cookiecutter",
    "template",
]

repository = "https://github.com/Materials-Data-Science-and-Informatics/metador-extension-cookiecutter"
homepage = "https://materials-data-science-and-informatics.github.io/metador-extension-cookiecutter"
documentation = "https://materials-data-science-and-informatics.github.io/metador-extension-cookiecutter"

[[project.people]]
given-names = "Anton"
family-names = "Pirogov"
email = "a.pirogov@fz-juelich.de"
orcid = "https://orcid.org/0000-0002-5077-7497"

author = true
maintainer = true

[config]
verbose = false
